-- -------------------------------------------------------------------------------------------------
-- Database Name: inji_mimoto
-- Purpose      : Rollback from 0.22.0 to 0.21.0
--
-- No database schema changes are required for this version transition.
-- -------------------------------------------------------------------------------------------------
