-- -------------------------------------------------------------------------------------------------
-- Database Name: inji_mimoto
-- Purpose      : Upgrade from 0.22.0 to 1.0.0
--
-- No database schema changes are required for this version transition.
-- -------------------------------------------------------------------------------------------------
